[package]
authors = ['Akropolis <admin@akropolis.io>']
build = 'build.rs'
edition = '2018'
name = 'akropolisos-substrate-node'
version = '0.2.1'

[dependencies]
error-chain = '0.12'
exit-future = '0.1'
futures = '0.3.1'
hex-literal = '0.1'
log = '0.4'
parity-codec = '3.2'
parking_lot = '0.7.1'
tokio = '0.1'
trie-root = '0.12.0'

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sc-basic-authority"

[dependencies.consensus]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
package = 'sc-consensus-aura'

[dependencies.grandpa]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sc-finality-grandpa"
version = "2.0.0"

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-network'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.akropolisos-substrate-node-runtime]
path = 'runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sc-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sc-client]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'
version = "2.0.0"

[dependencies.sc-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sc-service]
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.telemetry]
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-telemetry'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[build-dependencies]
vergen = '3'
[profile.release]
panic = 'unwind'

[[bin]]
name = 'akropolisos-substrate-node'
path = 'src/main.rs'
