[features]
default = ['std']
std = [
    'codec/std',
    'primitives/std',
    'rstd/std',
    'runtime-io/std',
    'support/std',
    'balances/std',
    'executive/std',
    'aura/std',
    'indices/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'session/std',
    'staking/std',
    'democracy/std',
    'contracts/std',
    'serde',
    'safe-mix/std',
    'aura-primitives/std',
    'offchain-primitives/std',
    'grandpa/std',
    'finality-tracker/std',
]

[package]
authors = ['Akropolis <admin@akropolis.io>']
edition = '2018'
name = 'akropolisos-substrate-node-runtime'
version = '0.3.0'

[dependencies.aura]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "pallet-aura"
default-features = false
version = "2.0.0"

[dependencies.consensus]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sp-consensus"
version = "0.8"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sp-consensus-aura"
default-features = false
version = "0.8"

[dependencies.balances]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "pallet-balances"
default-features = false
version = "2.0.0"

[dependencies.client]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sc-client"
version = "2.0.0"

[dependencies.executive]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "frame-executive"
default-features = false
version = "2.0.0"

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"
default-features = false
features = ["derive"]

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-std'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0'

[dependencies.sudo]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "pallet-sudo"
default-features = false
version = "2.0.0"

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-session]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
default-features = false
package = 'sp-session'
version = "2.0.0"

[dependencies.session]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
default-features = false
package = 'pallet-session'
version = "2.0.0"

[dependencies.staking]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-staking'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.democracy]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-democracy'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.contracts]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-contracts'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.grandpa]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.finality-tracker]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-finality-tracker'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.block-builder-api]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sp-block-builder"
default-features = false

[dependencies.sp-api]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
default-features = false
version = "2.0.0"

[dependencies.transaction-payment]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "pallet-transaction-payment"
default-features = false
version = "2.0.0"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sp-inherents"
default-features = false

[dependencies.sp-transaction-pool]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "sp-transaction-pool"
default-features = false
version = "2.0.0"

[dependencies.randomness-collective-flip]
git = "https://github.com/paritytech/substrate.git"
rev = "3e651110aa06aa835790df63410a29676243fc54"
package = "pallet-randomness-collective-flip"
default-features = false
version = "2.0.0"