name: PR
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly and wasm utils
      run: sh scripts/init.sh
    - name: Build WASM
      run: sh scripts/build.sh
    - name: Build runtime
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose